# Generated by Django 5.1 on 2024-08-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='date_posted',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post_model',
            name='post_image',
            field=models.ImageField(default='media/post_images/FB_IMG_16607757619264546.jpg', upload_to='media/post_images'),
        ),
    ]
