# Generated by Django 5.1 on 2024-08-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_model_date_posted_post_model_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='date_posted',
        ),
    ]
