# Generated by Django 5.1 on 2024-08-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_model_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='post_image',
            field=models.ImageField(default='post_images/FB_IMG_16607757619264546.jpg', upload_to='post_images/'),
        ),
    ]
