# Generated by Django 5.1 on 2024-08-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_model_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='author',
        ),
    ]
