# Generated by Django 5.1 on 2024-08-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_post_model_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='author',
            field=models.CharField(default='skrrr', max_length=400),
        ),
    ]
