# Generated by Django 5.1 on 2024-08-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_model_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='content',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
