# Generated by Django 5.1 on 2024-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_model_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
