# Generated by Django 5.1 on 2024-08-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_model_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='created',
        ),
    ]
