# Generated by Django 5.1 on 2024-08-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_post_model_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
