# Generated by Django 5.1 on 2024-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_remove_post_model_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image/'),
        ),
    ]
